# Generated by Django 4.0 on 2023-07-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0007_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False, verbose_name='В закладках'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Нравится'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
        ),
    ]
